### ISSUE TITLE
建议将快捷键全部改成”Alt+“形式，否则在某些网页上会出现错误，影响正常输入。

### ISSUE THREAD

**Issue by Charlestar** [smallx/monkey-scripts#1]
就我目前发现的，误触快捷键发生的有两个场景：①在腾讯在线文档的excel表格中，按下s会触发快捷键，弹出搜索框，导致无法输入以s开头的字和词。②在哔哩哔哩中，将视频分享到动态时，在输入“分享理由”时，按下w会自动弹出https://baike.baidu.com/ 的页面，也导致无法正常进行输入。

**Comment by smallx** [comment]
已优化, v1.4, 见 https://greasyfork.org/zh-CN/scripts/408250
