### ISSUE TITLE
Quick Search直链访问出错

### ISSUE THREAD

**Issue by Charlestar** [smallx/monkey-scripts#3]
在使用Quick Search直接访问选中的链接时，有时会在链接前添加www.和其他信息从而导致进入页面失败。例如访问：
https://github.com/BWmelon/qrcode
使用Quick Search访问到的是：
http://www.https//github.com/BWmelon/qrcode

**Comment by smallx** [comment]
v1.5已修复, 见 https://greasyfork.org/zh-CN/scripts/408250
