### ISSUE TITLE
在搜索框(包括baidu、google和论坛等等)内粘贴复制的内容时会经常失败

### ISSUE THREAD

**Issue by SmukamiP** [smallx/monkey-scripts#5]
![1](https://user-images.githubusercontent.com/13297366/94528003-63daba80-026a-11eb-83da-fe709723c543.gif)

**Comment by smallx** [comment]
这个是因为配置中默认启用了"划词自动复制到剪贴板"功能, 在设置中把"autoCopyToClipboard"设置为false或0就可以了.

按Alt+F键打开主窗口, 然后步骤如下:

![image](https://user-images.githubusercontent.com/16517035/94549954-9219c380-0285-11eb-9b1e-d5b19c14b47b.png)

ps: 你这个gif截屏软件是啥, windows上的吗

**Comment by SmukamiP** [comment]
好的，我知道了，谢谢解答！
我用的gif截屏软件是ScreenToGif，是windows平台上的，
地址：https://github.com/NickeManarin/ScreenToGif/releases

**Comment by smallx** [comment]
💯
