### ISSUE TITLE
multi-search配合Super_preloaderPlus_one插件使用的问题

### ISSUE THREAD

**Issue by licoba** [smallx/monkey-scripts#6]
- 问题
左边可以自动下一页，但是右边不能自动翻页

- 补充
（当然这也可能是Super_preloaderPlus_one插件的问题）

- 希望
希望左右两边能同时自动翻页😁

**Comment by garypang13** [comment]
同样的问题,纠结,

**Comment by smallx** [comment]
@licoba @garypang13 
multi-search脚本可以改一下, 改成一次搜索20条(其实脚本中有).
不过, 右边的搜索引擎只当是辅助, 20条基本够了.
